[package]

name = "hippo"
version = "0.0.1"
authors = [ "Nick Hamann <nick@wabbo.org>" ]

[[bin]]

name = "hippo"

[dependencies]
docopt = "*"
rustc-serialize = "*"
rusqlite = "0.0.10"
time = "~0.1.0"

